# Generated by Django 5.2 on 2025-04-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_itineraryday_activities_itinerary_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="location_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
